spring:
  application:
    name: allmart_api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/djdb
    username: djdbuser
    password: djdbuser
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      location: ${org.allmart_api.upload.path}

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: allmart-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      max.poll.records: 500
    admin:
      fail-fast: true
    streams:
      application-id: allmart-streams-app
      state-dir: /tmp/kafka-streams

org:
  allmart_api:
    accessTime: 60
    refreshTime: 1440
    alwaysNew: true
    upload:
      path: C:/upload

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
