spring:
  application:
    name: allmart_api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:13306/test
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      location: ${org.allmart_api.upload.path}  # 업로드 경로를 org.sunbong.upload.path와 연동
  config:
    import: optional:file:.env[.properties]

org:
  allmart_api:
    accessTime: 60
    refreshTime: 1440
    alwaysNew: true
    upload:
      path: ${UPLOAD_PATH}

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder:
kakao:
  KAKAO_MAP_API_KEY: ${KAKAO_MAP_API_KEY}
  KAKAO_GEO_API_KEY: ${KAKAO_GEO_API_KEY}
toss:
  SECRET_KEY: ${TOSS_SECRET_KEY}
