spring:
  application:
    name: allmart_api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jindb # Docker MariaDB Source
    username: useruser
    password: useruser
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 10000
  data:
    redis:
      host: redis # Redis 컨테이너 이름
      port: 6379  # Redis 기본 포트

  jpa:
    hibernate:
      connection.isolation: 2 # READ COMMITTED
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      location: ${org.allmart_api.upload.path}  # 업로드 경로 설정
  config:
    import: optional:file:.env[.properties]

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS} # 환경 변수 사용
    consumer:
      group-id: delivery-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        fetch.max.bytes: 200000000 # 약 200MB
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.request.size: 200000000 # 약 200MB
    admin:
      fail-fast: true
    properties:
      max.poll.records: 500
    topics:
      dlq: vgdb.vgdb.tbl_outbox.dlq
    streams:
      application-id: delivery-stream-app
      state-dir: /data/kafka-streams
      properties:
        commit.interval.ms: 100
        statestore.cache.max.bytes: 10485760
        replication.factor: 1
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
org:
  allmart_api:
    accessTime: 60
    refreshTime: 1440
    alwaysNew: true
    upload:
      path: ${UPLOAD_PATH}

logging:
  level:
    org:
      hibernate:
        SQL: INFO
kakao:
  KAKAO_MAP_API_KEY: ${KAKAO_MAP_API_KEY}
  KAKAO_GEO_API_KEY: ${KAKAO_GEO_API_KEY}
toss:
  SECRET_KEY: ${TOSS_SECRET_KEY}
