name: CI/CD Pipeline for Spring Boot on Amazon Linux (No Docker)

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Amazon Corretto JDK 설정
      - name: Set up Amazon Corretto JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # 3. Gradle 캐시 사용 (빌드 속도 향상)
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. gradlew에 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. Gradle 빌드 및 테스트 실행
      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon

      #      - name: Run Tests
      #        run: ./gradlew test --no-daemon

      # 6. 빌드 결과물 업로드 (JAR 파일)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: build/libs/*.jar

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. 빌드 결과물 다운로드
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-app
          path: . # 현재 디렉토리로 다운로드

      # 2. EC2에 파일 전송 및 배포 실행
      - name: Deploy to EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ec2-user # Amazon Linux 기본 사용자 이름
          ENV_CONTENT: ${{ secrets.ENV_CONTENT }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

          # 다운로드한 JAR 파일 확인
          ls -al
          
          # JAR 파일 이름 변경 및 전송
          JAR_FILE=$(ls *.jar | grep -v plain)
          
          scp -o StrictHostKeyChecking=no -i private_key ${JAR_FILE} ${USERNAME}@${HOST}:/opt/myapp/app.jar
          
          
          # EC2에서 배포 스크립트 실행
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOST} << EOF
            sudo yum update -y
            sudo yum install -y java-17-amazon-corretto-devel

            # 환경 변수 파일 생성
            echo "${ENV_CONTENT}" > /opt/myapp/.env

            # 기존 프로세스 중지 (프로세스 이름으로 변경해주세요)
            sudo pkill -f "java -jar /opt/myapp/app.jar" || true
          
            # systemd 서비스 재시작 (myapp.service는 사전에 설정되어 있어야 함)
            sudo systemctl daemon-reload
            sudo systemctl restart myapp.service || sudo systemctl start myapp.service

            # 서비스 상태 확인
            sudo systemctl status myapp.service || true
          EOF